# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - src/DHI.Mesh/*
    - src/DHI.Mesh.Test/*

pool:
  name: Hosted VS2017

variables:
  BuildConfiguration: release

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/DHI.Mesh.csproj'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/DHI.Mesh.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Test*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/DHI.Mesh.csproj'
    versioningScheme: byPrereleaseNumber
    minorVersion: 0

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    publishVstsFeed: 'bdb47caa-942e-42e3-803f-8bcae759f218'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
