name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**' 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/DHI.Mesh.sln -s https://api.nuget.org/v3/index.json 
    - name: Build
      run: dotnet build ./src/DHI.Mesh.sln --no-restore
    - name: Test
      run: dotnet test ./src/DHI.Mesh.Test/DHI.Mesh.Test.csproj --no-build --verbosity normal
